Controllers/MachineController/MachineController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CySim.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CySim.Controllers.MachineController
{
    public class MachineController : Controller
    {
        [HttpGet]
        public IActionResult Machine()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MachineController/MachineInfoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CySim.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CySim.Controllers.MachineController
{
    public class MachineInfoController : Controller
    {
        [HttpGet]
        public IActionResult MachineInfo()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ScenarioController/ScenarioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CySim.Data;
using CySim.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using CySim.Models.Scenario;
using System.IO.Abstractions;


namespace CySim.Controllers
{
    [Authorize]
    public class ScenarioController : Controller
    {
        private readonly ILogger<ScenarioController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly IFileSystem _fileSystem;

        public ScenarioController(ILogger<ScenarioController> logger, ApplicationDbContext context, IFileSystem fileSystem)
        {
            _logger = logger;
            _context = context;
            _fileSystem = fileSystem;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Scenarios.OrderBy(x => x.isRed).ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(IFormFile file, String Description, bool isRed)
        {
            TempData["errors"] = "";

            if (file == null)
            {
                _logger.LogError("Scenario Create: No file was uploaded");
                TempData["errors"] = "No file was uploaded";
                return RedirectToAction(nameof(Create));
            }
            if (Description == null)
            {
                _logger.LogError("Scenario Create: No Description was entered");
                TempData["errors"] = "No description was provided";
                return RedirectToAction(nameof(Create));
            }

            var fileName = file.FileName;

            if (await _context.Scenarios.AnyAsync(x => x.FileName == fileName))
            {
                _logger.LogError("Scenario Create: FileName of uploaded file matched another scenario");
                TempData["errors"] = "Sorry this file name already exist";
                return RedirectToAction(nameof(Create));
            }

            var filePath = Path.Combine("Documents/Scenario", fileName);

            using (var stream = _fileSystem.FileStream.New(Path.Combine("wwwroot", filePath), FileMode.Create))
            {
                await file.CopyToAsync(stream);
                _logger.LogInformation("Scenario Create: File was uploaded to Documents/Scenario");
            }

            var scenario = new Scenario()
            {
                FileName = fileName,
                FilePath = filePath,
                Description = Description,
                isRed = isRed,
            };

            if (ModelState.IsValid)
            {
                _context.Add(scenario);
                await _context.SaveChangesAsync();

                _logger.LogInformation("Scenario Create: New database entry created");

                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Create));
        }


        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            var scenario = await _context.Scenarios.FindAsync(id);
            if (scenario == null)
            {
                _logger.LogError("Scenario Delete on id = " + id + ": No scenario has id = " + id);
                return NotFound();
            }

            var fileName = Path.Combine("wwwroot", scenario.FilePath);

            if (ModelState.IsValid && _fileSystem.File.Exists(fileName))
            {
                _fileSystem.File.Delete(fileName);
                _context.Scenarios.Remove(scenario);
                await _context.SaveChangesAsync();
                _logger.LogInformation("Scenario Delete on id = " + id + ": " + fileName + " was deleted and database entry removed");
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit([FromRoute] int id)
        {
            var scenario = await _context.Scenarios.FindAsync(id);
            if (scenario == null)
            {
                _logger.LogError("Scenario Edit on id = " + id + ": No scenario has id = " + id);
                return NotFound();
            }

            return View(scenario);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] int id, IFormFile file, String FileName, String Description, bool isRed)
        {
            // HTML Form Error Handling 
            TempData["errors"] = "";

            var scenario = await _context.Scenarios.FindAsync(id);
            if (scenario == null)
            {
                _logger.LogError("Scenario Edit on id = " + id + ": No scenario has id = " + id);
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                _logger.LogError("Scenario Edit on id = " + id + ": Model state was invalid");

                var errorMessage = string.Join("; ", ModelState.Values
                                    .SelectMany(x => x.Errors)
                                    .Select(x => x.ErrorMessage));
                _logger.LogError("Model state errors messages: " + errorMessage);

                return RedirectToAction(nameof(Edit), new { id = id });
            }

            if (FileName == null)
            {
                _logger.LogError("Scenario Edit on id = " + id + ": No FileName was entered");
                TempData["errors"] = "No file name was provided";
                return RedirectToAction(nameof(Edit), new { id = id });
            }

            if (await _context.Scenarios.AnyAsync(x => x.Id != id && x.FileName == FileName))
            {
                _logger.LogError("Scenario Edit on id = " + id + ": FileName matched another scenario");
                TempData["errors"] = "This file name is already used by another scenario";
                return RedirectToAction(nameof(Edit), new { id = id });
            }

            if (Description == null)
            {
                _logger.LogError("Scenario Edit on id = " + id + ": No Description was entered");
                TempData["errors"] = "No description was provided";
                return RedirectToAction(nameof(Edit), new { id = id });
            }


            var CurrFile = Path.Combine("wwwroot", scenario.FilePath);
            var NewFile = Path.Combine("wwwroot/Documents/Scenario", FileName);

            // Replace file contents
            if (file != null)
            {
                using (var stream = _fileSystem.FileStream.New(CurrFile, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                _logger.LogInformation("Scenario Edit on id = " + id + ": File contents were replaced by uploaded file");
            }

            // Rename file
            if (CurrFile != NewFile)
            {
                _fileSystem.File.Move(CurrFile, NewFile);
                _logger.LogInformation("Scenario Edit on id = " + id + ": File was renamed");
            }

            // Update scenario variable
            scenario.FileName = FileName;
            scenario.FilePath = Path.Combine("Documents/Scenario", FileName);
            scenario.Description = Description;
            scenario.isRed = isRed;

            _context.Scenarios.Update(scenario);
            await _context.SaveChangesAsync();

            _logger.LogInformation("Scenario Edit on id = " + id + ": Database entry was updated");

            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            _logger.LogError("User made an error at scenario controller");
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/Tutorial/TutorialController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CySim.Controllers.TeamRegistration;
using CySim.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;



namespace CySim.Controllers.Tutorial
{
	public class TutorialController : Controller
	{

        private readonly ILogger<TutorialController> _logger;

        public TutorialController(ILogger<TutorialController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            _logger.LogInformation("User made an error at Tutrial controller");
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CySim</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CySim</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TeamRegistration" asp-action="Index">Team Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ScoreBoard" asp-action="ScoreBoard">ScoreBoard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tutorial" asp-action="Index">Tutorial</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Scenario" asp-action="Index">Scenario</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Machine
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="Machine" asp-action="Machine">Machines</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-controller="MachineInfo" asp-action="MachineInfo">Machine Info</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-controller="MachineStatus" asp-action="MachineStatus">Machine Status</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CySim - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_TableButtonPartial.cshtml
@model int

<td colspan="2">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary rounded-true" href="@Url.Action("Join", new { id = Model})"><i class="fa-regular fa-pen-to-square"></i></a>
    </div>
</td>


<td align="left" colspan="2">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary rounded-true" href="@Url.Action("Edit", new { id = Model})"><i class="fa-regular fa-pen-to-square"></i></a>
        @*<a type="button" class="btn btn-primary" href="@Url.Action("Delete", new { id = item.Id})">Delete</a>*@
        <form method="post" action="Delete">
            <button onclick="if (!confirm('Are you sure you want to delete this?')){ return false }" type="submit" class="btn btn-danger rounded-true" asp-action="Delete" asp-route-id="@Model"> <i class="fa-solid fa-trash"></i> </button>
        </form>
    </div>
</td>